version: "3.9"

services:
  # The Cookie Factory backend in SpringBoot
  tcf-server:
    image: teamb/w4e-spring-backend
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - BANK_WITH_PORT=bank-system:9090
      - SCHEDULER_WITH_PORT=scheduler-system:9091
      - SKIPASS_WITH_PORT=skipass-system:9092
      - POSTGRES_HOST=postgres:5432
    entrypoint: "java -jar /opt/app/app.jar --bank.host.baseurl=http://$${BANK_WITH_PORT} --scheduler.host.baseurl=http://$${SCHEDULER_WITH_PORT}"
    restart: always
    depends_on:
      bank-system:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: "curl --silent --fail localhost:8080/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  # the postgres DB to be connected to the backend (watch out: no volume specified, everything can be lost)
  postgres:
    image: postgres:16.1
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_USER=postgresuser
      - POSTGRES_DB=tcf-db
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d tcf-db -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  # A simple java CLI
  tcf-cli:
    image: teamb/w4e-spring-cli
    container_name: cli
    environment:
      - SERVER_WITH_PORT=tcf-server:8080
    entrypoint: "java -jar /opt/app/app.jar"
    depends_on:
      tcf-server:
        condition: service_healthy
    volumes:
      - ./cli/demo.txt:/opt/app/demo.txt
    stdin_open: true
    tty: true
    healthcheck:
      test: "curl --silent --fail localhost:8081/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  # An external bank service in NestJs
  bank-system:
    image: teamb/w4e-bank-service
    container_name: bank
    ports:
      - 9090:9090
    healthcheck:
      test: [ "CMD", "/nodejs/bin/node" , "healthcheck.js" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  scheduler-system:
    image: teamb/w4e-scheduler-service
    container_name: scheduler
    ports:
      - 9091:9091
    healthcheck:
      test: [ "CMD", "/nodejs/bin/node" , "healthcheck.js" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  skipass-system:
    image: teamb/w4e-skipass-service
    container_name: skipass
    ports:
      - 9092:9092
    healthcheck:
      test: [ "CMD", "/nodejs/bin/node" , "healthcheck.js" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
